version: 2

sources:
  - name: raw_data
    description: "Raw data sources for NYC taxi rides"
    database: de-zoomcamp-dbt # project id 
    schema: ny_taxi # dataset
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: data_test